image: node:latest

stages:
  - build
  - test

install_dependencies:
  stage: build
  script:
    - cd testlet
    - npm install
    - npx cypress install
    - if [ $? -ne 0 ]; then exit 1; fi

run_test:
  stage: test
  script:
    - npx cypress run-ct --browser chrome
  only:
    - merge_requests
    - main
  artifacts:
    when: always
    paths:
      - testlet/cypress/screenshots/
      - testlet/cypress/videos/