image: node:latest

stages:
  - compile
  - test

build_app:
  stage: compile
  script:
    - cd testlet
    - npm install
    - npm run dev

cypress_testing:
  stage: test
  script:
    - cd testlet
    - npx cypress run --browser chrome
  only:
    - merge_requests
    - main
  artifacts:
    when: always
    paths:
      - testlet/cypress/screenshots/
      - testlet/cypress/videos/