image: cypress/base:16.13.0

cache:
  key: '${CI_COMMIT_REF_SLUG}'
  paths:
    - node_modules/
    - .cache/Cypress

stages:
  - test

test:
  stage: test
  script:
    - npm ci
    - npx cypress verify
    - npx cypress run --config-file cypress.json
  artifacts:
    when: always
    paths:
      - cypress/videos
      - cypress/screenshots
