image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test

cypress_test:
  stage: test
  script:
    - echo "Current directory:"
    - pwd
    - echo "List directory content:"
    - ls -la
    - npm install
    - npx cypress install
    - npx cypress run-ct --browser chrome
  artifacts:
    when: always
    paths:
      - cypress/videos/
      - cypress/screenshots/
  only:
    - merge_requests
    - main
