image: mcr.microsoft.com/windows/servercore:ltsc2019

stages:
  - test

variables:
  CI_DEBUG_TRACE: "true"

test:
  stage: test
  script:
    - npm ci
    - npm run test:ci
  artifacts:
    paths:
      - cypress/videos/
      - cypress/screenshots/

windows:
  stage: test
  script:
    - npm ci
    - npm run test:ci
  artifacts:
    paths:
      - cypress/videos/
      - cypress/screenshots/
  tags:
    - windows
  except:
    - triggers
