image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test

cypress_test:
  stage: test
  script:
    - npm ci
    - npx cypress install
    - npx cypress run
  artifacts:
    when: always
    paths:
      - cypress/videos/
      - cypress/screenshots/
  only:
    - merge_requests
    - master

