image: node:latest

stages:
  - compile
  - test
  - deploy

compile_website:
  stage: compile
  script:
    - cd testlet
    - npm install
    - npm run dev

cypress_testing:
  stage: test
  script:
    - cd testlet
    - npx cypress run --browser chrome
  only:
    - merge_requests
    - main
  artifacts:
    when: always
    paths:
      - testlet/cypress/screenshots/
      - testlet/cypress/videos/

end_event:
  stage: deploy
  script:
    - echo "Event has ended"
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push" && $CI_BUILD_STATUS == "success"
      when: always