image: node:latest

stages:
  - build
  - test

install_dependencies_and_run_tests:
  stage: build
  script:
    - cd testlet
    - npm ci
    - npx cypress install
    - npx cypress run-ct --browser chrome
  only:
    - merge_requests
    - main
  artifacts:
    paths:
        - testlet/
