image: node:latest

stages:
  - compile
  - test

compile_website:
  stage: compile
  script:
    - cd testlet
    - npm install
    - sleep 10
    - pkill -f "node.*\.next.*"

cypress_testing:
  stage: test
  script:
    - cd testlet
    - npx cypress run --browser chrome
  only:
    - merge_requests
    - main
  artifacts:
    when: always
    paths:
      - testlet/cypress/screenshots/
      - testlet/cypress/videos/