image: node:latest

stages:
  - compile
  - test

compile_website:
  stage: compile
  script:
    - cd testlet
    - npm install
    - npm run dev &
    - DEV_PID=$! # capture the PID of the dev process
    - wait $DEV_PID # wait for the dev process to complete
    - kill $DEV_PID # kill the dev process

cypress_testing:
  stage: test
  script:
    - cd testlet
    - npx cypress run --browser chrome
  only:
    - merge_requests
    - main
  artifacts:
    when: always
    paths:
      - testlet/cypress/screenshots/
      - testlet/cypress/videos/