
test:
  # Use the official Node.js Docker image
  image: node:latest

  # Define cache paths for faster builds
  cache:
    paths:
      - node_modules/

  # Define services for the tests to use
  services:
    - name: firebase
      alias: firebase
      entrypoint:
        - /usr/bin/entrypoint
        - -r
        - "us-central1"
        - --token
        - "supersecret"

  # Define the script to run the tests
  script:
    - npm install
    - npm run build

