image: node:latest

cache:
  paths:
    - testlet/node_modules/

stages:
  - build
  - test

install_dependencies:
  stage: build
  script:
    - cd testlet
    - npm ci
    - npx cypress install

run_test:
  stage: test
  script:
    - npx cypress run-ct --browser chrome

artifacts:
  trigger:
    - merge_requests
    - main
  paths:
    - testlet/

only:
    - merge_requests
    - main