image: node:latest

stages:
  - build
  - test

install_dependencies:
  stage: build
  script:
    - cd testlet
    - npm ci

cypress_testing:
  stage: test
  script:
    - cd testlet
    - npx cypress run --browser chrome
  only:
    - merge_requests
    - main
  artifacts:
    when: always
    paths:
      - testlet/cypress/videos/