image: node:latest

stages:
  - test


cypress_testing:
  stage: test
  script:
    - cd testlet
    - npm ci
    - npx cypress run --browser chrome
  only:
    - merge_requests
    - main
  artifacts:
    when: always
    paths:
      - testlet/cypress/videos/