image: node:latest

stages:
  - compile
  - test

compile_website:
  stage: compile
  script:
    - cd testlet
    - npm install
    - timeout 20s npm run dev > npm_run.log || FAILED=true  # if it fails, the variable is set up
    - grep -e 'listening on \*:3000' npm_run.log

cypress_testing:
  stage: test
  script:
    - cd testlet
    - npx cypress run --browser chrome
  only:
    - merge_requests
    - main
  artifacts:
    when: always
    paths:
      - testlet/cypress/screenshots/
      - testlet/cypress/videos/