image: node:latest

stages:
  - build
  - test

install_dependencies:
  stage: build
  script:
    - cd testlet
    - npm ci
    - npx cypress install

run_test:
  stage: test
  script:
    - npx cypress run-ct --browser chrome
  only:
    - merge_requests
    - main
  artifacts:
    paths:
        - testlet/